version: '3'

services:
  web:
    build: ./app
    container_name: eip
    command: python3 manage.py runserver 0.0.0.0:80 --insecure
    restart: unless-stopped
    volumes:
      - ./app:/app/
      - staticfiles:/app/static/
      - mediafiles:/app/media/
    ports:
      - 80:80
    env_file:
      - ./.env

volumes:
  staticfiles:
  mediafiles: