# Generated by Django 3.1.7 on 2021-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='post'),
        ),
    ]
