# Generated by Django 3.1.7 on 2021-04-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0003_auto_20210403_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='noAvatar.jpg', upload_to='profile'),
        ),
    ]
