# Generated by Django 3.1.7 on 2021-04-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
