# Generated by Django 3.1.7 on 2021-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0011_auto_20210403_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/profile/noAvatar.jpg', upload_to='profile'),
        ),
    ]
