# Generated by Django 3.1.7 on 2021-08-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ether', '0013_userfriends_userguild_userinventory_userposition_userskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userskills',
            unique_together={('author',)},
        ),
    ]
