# Generated by Django 3.1.7 on 2021-09-04 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ether', '0014_auto_20210831_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userskills',
            unique_together={('cap_1', 'cap_2', 'cap_3', 'cap_4')},
        ),
    ]
