# Generated by Django 3.1.7 on 2021-09-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0015_auto_20210904_1032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskills',
            unique_together=set(),
        ),
    ]
