# Generated by Django 3.1.7 on 2021-09-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0017_auto_20210904_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfriends',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userguild',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinventory',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userpositions',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userskills',
            old_name='author',
            new_name='user',
        ),
    ]
