# Generated by Django 3.1.7 on 2021-09-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0021_auto_20210906_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'Data'},
        ),
    ]
