# Generated by Django 3.1.7 on 2022-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0026_auto_20210906_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='gem',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='gold',
        ),
        migrations.AddField(
            model_name='userdata',
            name='cash',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='crystal',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='hasDoneTutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='maxTextureSlot',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='textureSlot',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
