# Generated by Django 3.1.7 on 2022-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0030_usertexture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertexture',
            name='texture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
