# Generated by Django 4.0.4 on 2022-05-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0031_auto_20220307_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertexture',
            name='name',
        ),
    ]
