# Generated by Django 4.0.4 on 2022-05-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0032_remove_usertexture_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinventory',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userinventory',
            old_name='number',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='userinventory',
            name='_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinventory',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
