# Generated by Django 4.0.4 on 2022-05-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ether', '0035_rename_cap_1_userskills_name_remove_userskills_cap_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTexture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.BinaryField(blank=True, editable=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Commutary Textures Shop',
            },
        ),
    ]
