# Generated by Django 4.0.4 on 2022-11-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0041_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='skinId',
            field=models.IntegerField(default=0),
        ),
    ]
