# Generated by Django 4.0.4 on 2022-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0042_userdata_skinid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='skinId',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
