# Generated by Django 3.1.7 on 2021-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.CharField(max_length=254),
        ),
    ]
