# Generated by Django 3.1.7 on 2021-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0002_auto_20210330_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.EmailField(max_length=254),
        ),
    ]
