# Generated by Django 3.1.7 on 2021-03-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0002_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter'},
        ),
    ]
