# Generated by Django 3.1.7 on 2021-03-31 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0003_auto_20210331_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('alpha', models.BooleanField(blank=True, default=False, null=True)),
                ('beta', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alpha / Beta',
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Registered'),
        ),
    ]
