# Generated by Django 3.1.7 on 2021-03-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0004_auto_20210331_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
