# Generated by Django 3.1.7 on 2021-03-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0005_auto_20210331_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter'},
        ),
    ]
