# Generated by Django 3.1.7 on 2021-03-31 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ether', '0006_auto_20210331_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='email',
        ),
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
