# Generated by Django 3.1.7 on 2021-04-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
