# Generated by Django 3.1.7 on 2021-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0008_auto_20210403_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='noAvatar.jpg', upload_to='profile'),
        ),
    ]
