# Generated by Django 3.1.7 on 2021-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether', '0010_auto_20210403_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='noAvatar.jpg', upload_to='profile'),
        ),
    ]
